'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property YourItems() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("YourItems"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("YourItems") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property YourItems1() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("YourItems1"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("YourItems1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property YourItems2() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("YourItems2"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("YourItems2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property YourItems3() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("YourItems3"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("YourItems3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property YourItems4() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("YourItems4"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("YourItems4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property YourItems5() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("YourItems5"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("YourItems5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property YourItems6() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("YourItems6"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("YourItems6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property YourItems7() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("YourItems7"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("YourItems7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property check1() As Boolean
            Get
                Return CType(Me("check1"),Boolean)
            End Get
            Set
                Me("check1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("elektrometal")>  _
        Public Property dtb1() As String
            Get
                Return CType(Me("dtb1"),String)
            End Get
            Set
                Me("dtb1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property check2() As Boolean
            Get
                Return CType(Me("check2"),Boolean)
            End Get
            Set
                Me("check2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\ProgramData\tedhena_backup.accdb")>  _
        Public Property backup() As String
            Get
                Return CType(Me("backup"),String)
            End Get
            Set
                Me("backup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property logo() As String
            Get
                Return CType(Me("logo"),String)
            End Get
            Set
                Me("logo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property tvsh() As String
            Get
                Return CType(Me("tvsh"),String)
            End Get
            Set
                Me("tvsh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ruajraportet() As String
            Get
                Return CType(Me("ruajraportet"),String)
            End Get
            Set
                Me("ruajraportet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property faturatofert() As String
            Get
                Return CType(Me("faturatofert"),String)
            End Get
            Set
                Me("faturatofert") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ruajgjendjen() As String
            Get
                Return CType(Me("ruajgjendjen"),String)
            End Get
            Set
                Me("ruajgjendjen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ruajdtbpath() As String
            Get
                Return CType(Me("ruajdtbpath"),String)
            End Get
            Set
                Me("ruajdtbpath") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Inventar_Database.My.MySettings
            Get
                Return Global.Inventar_Database.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
